(ns joker.handler
  (:require [compojure.core :refer :all]
            [compojure.handler :as handler]
            [compojure.route :as route]))

;; (def stop)
(comment
  ;; magic lib
  (require '[vinyasa.pull :as vp]))

(comment
  ;; autogenerated content
  (defroutes app-routes
    (GET "/" [] "Hello World")
    (route/resources "/")
    (route/not-found "Not Found"))

  (def app
    (handler/site app-routes)))
